### ISSUE TITLE
class_error: 0.00                        has no chanege, how to solve it？

### ISSUE THREAD

**Issue by Issac304** [Sampson-Lee/DSCT#3]
class_error: 0.00                        has no chanege, how to solve it？

**Comment by Issac304** [comment]
![image](https://github.com/user-attachments/assets/333ccb94-f92b-4c68-8b29-9776834673b0)

**Comment by Issac304** [comment]
the acc is so low, how to fix it？

**Comment by Sampson-Lee** [comment]
Hi, thanks for the question. What is the context of the issuse? I guess you're doing experiments on emotic. If so, the accuracy is non-sense for emotic dataset since it is a multi-label dataset.

**Comment by Issac304** [comment]
Thans for your reply!
Yes, i 'am doing experiments on emotic.
the accuracy is non-sense for emotic, i understand now.
and so i need to train on the&nbsp;CAER-S&nbsp; from start or from the emotic 's pth file?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sampson-Lee/DSCT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月28日(星期四) 晚上11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sampson-Lee/DSCT] class_error: 0.00                        has no chanege, how to solve it？ (Issue #3)





 
Hi, thanks for the question. What is the context of the issuse? I guess you're doing experiments on emotic. If so, the accuracy is non-sense for emotic dataset since it is a multi-label dataset.
